# Sử dụng Nginx image làm cơ sở
FROM nginx:latest

# Copy nội dung của templateweb1 vào thư mục web1 trong container
COPY template/templateweb1 /usr/share/nginx/html/web1

# Copy nội dung của templateweb2 vào thư mục web2 trong container
COPY template/templateweb2 /usr/share/nginx/html/web2
