apiVersion: v1
kind: Service
metadata:
  name: web1-service
spec:
  selector:
    app: web1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: web2-service
spec:
  selector:
    app: web2
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  type: NodePort
